/**
 * File generated by Figma Launchpad plugin
 * https://www.figma.com/community/plugin/1198744392213971918
 */

export default function App() {
  return (
    <div
      style={{
        position: "relative",
        height: 1024,
        backgroundColor: "#fbf9f7",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute",
          left: "50%",
          width: 1162,
          top: "50%",
          height: 621,
          backgroundColor: "#ffffff",
          borderRadius: 8,
          overflow: "hidden",
          transform: "translateX(-472px) translateY(-337px)",
        }}
      >
        <div
          style={{
            position: "absolute",
            left: 0,
            width: 1162,
            top: 0,
            height: 70,
            backgroundColor: "#fbf9f7",
            overflow: "hidden",
          }}
        >
          <p
            style={{
              position: "absolute",
              left: 30,
              width: "max-content",
              top: 23,
              color: "#000000",
              fontSize: 18,
              fontWeight: 500,
            }}
          >
            Basic Information
          </p>
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 30,
            position: "absolute",
            left: 30,
            top: 100,
          }}
        >
          <div
            style={{
              position: "relative",
              width: 80,
              flexShrink: 0,
              height: 80,
            }}
          >
            <div
              style={{
                position: "absolute",
                left: 0,
                width: 80,
                top: 0,
                height: 80,
              }}
            >
              <div
                style={{
                  position: "absolute",
                }}
              >
                <img
                  style={{
                    height: 80,
                    flexShrink: 0,
                    width: 80,
                    zIndex: 0,
                    borderRadius: "50%",
                  }}
                  src="/svg_2.svg"
                  alt=""
                />
                <img
                  style={{
                    height: 80,
                    flexShrink: 0,
                    width: 85,
                  }}
                  src="/img_3.jpg"
                  alt=""
                />
              </div>
              <div
                style={{
                  position: "absolute",
                  left: 60,
                  width: 24,
                  top: 51,
                  height: 24,
                }}
              >
                <img
                  style={{
                    position: "absolute",
                    left: 0,
                    width: 24,
                    top: 0,
                    height: 24,
                    borderRadius: "50%",
                  }}
                  src="/svg_4.svg"
                  alt=""
                />
                <img
                  style={{
                    position: "absolute",
                    left: 5.6015625,
                    width: 12.800000190734863,
                    top: 5.599609375,
                    height: 12.800000190734863,
                    overflow: "hidden",
                  }}
                  src="/svg_5.svg"
                  alt=""
                />
              </div>
            </div>
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: 4,
              flexShrink: 0,
            }}
          >
            <p
              style={{
                flexShrink: 0,
                width: "max-content",
                color: "#000000",
                fontSize: 16,
                fontWeight: 500,
              }}
            >
              Profile photo
            </p>
            <p
              style={{
                flexShrink: 0,
                width: "max-content",
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              This will be displayed on your profile.
            </p>
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 30,
            width: 330,
            top: 230,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_6.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Markh David
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Name
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 410,
            width: 330,
            top: 230,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_7.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                David123@.com
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Email Address
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 790,
            width: 330,
            top: 230,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_8.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                +4945296642182
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Phone No
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 30,
            width: 330,
            top: 335,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_9.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Male
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Gender
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 410,
            width: 330,
            top: 335,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_10.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                9/11/1985
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Date of Birth
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 790,
            width: 330,
            top: 335,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_11.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                10117
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Zip Code
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 30,
            width: 330,
            top: 440,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_12.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Account
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Department
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 410,
            width: 330,
            top: 440,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_13.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Berlin, Germany
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Live
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 790,
            width: 330,
            top: 440,
            height: 75,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 330,
              top: 29,
              height: 46,
              backgroundColor: "#fbf9f7",
              zIndex: 0,
              outlineStyle: "solid",
              outlineColor: "#dde2e8",
              outlineWidth: 1,
              outlineOffset: -1,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 15,
                top: 13,
                zIndex: -1,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                }}
              >
                <img
                  style={{
                    position: "relative",
                    width: 18,
                    flexShrink: 0,
                    height: 18,
                    overflow: "hidden",
                  }}
                  src="/svg_14.svg"
                  alt=""
                />
              </div>
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                St#296, Germany
              </p>
            </div>
          </div>
          <p
            style={{
              position: "absolute",
              left: 0,
              width: "max-content",
              top: 0,
              color: "#727272",
              fontSize: 14.220000267028809,
              fontWeight: 400,
            }}
          >
            Street Address
          </p>
        </div>
        <div
          style={{
            position: "absolute",
            left: 951,
            width: 169,
            top: 545,
            height: 46,
            backgroundColor: "#1ba9a0",
            borderRadius: 8,
            overflow: "hidden",
          }}
        >
          <p
            style={{
              position: "absolute",
              left: "50%",
              width: "max-content",
              top: "50%",
              color: "#ffffff",
              fontSize: 16,
              fontWeight: 500,
              transform: "translateX(-35.5px) translateY(-11px)",
            }}
          >
            Continue
          </p>
        </div>
      </div>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 30,
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translateX(-317px) translateY(-405px)",
        }}
      >
        <div
          style={{
            display: "flex",
            gap: 15,
            flexShrink: 0,
          }}
        >
          <div
            style={{
              position: "relative",
              width: 30,
              flexShrink: 0,
              height: 30,
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 0,
                width: 30,
                top: 0,
                height: 30,
                borderRadius: "50%",
              }}
              src="/svg_15.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 12,
                width: "max-content",
                top: 3,
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 500,
              }}
            >
              1
            </p>
          </div>
          <p
            style={{
              width: "max-content",
              flexShrink: 0,
              color: "#1ba9a0",
              fontSize: 22.780000686645508,
              fontWeight: 700,
            }}
          >
            Profile
          </p>
        </div>
        <div
          style={{
            width: 110,
            flexShrink: 0,
            height: 0,
            outlineStyle: "solid",
            outlineColor: "#dde2e8",
            outlineWidth: 1,
            outlineOffset: -0.5,
          }}
        />
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 15,
            flexShrink: 0,
          }}
        >
          <div
            style={{
              position: "relative",
              width: 30,
              flexShrink: 0,
              height: 30,
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 0,
                width: 30,
                top: 0,
                height: 30,
                borderRadius: "50%",
              }}
              src="/svg_16.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 9,
                width: "max-content",
                top: 3,
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 500,
              }}
            >
              2
            </p>
          </div>
          <p
            style={{
              width: "max-content",
              flexShrink: 0,
              color: "#c6c2c2",
              fontSize: 22.780000686645508,
              fontWeight: 700,
            }}
          >
            Billing Address
          </p>
        </div>
        <div
          style={{
            width: 110,
            flexShrink: 0,
            height: 0,
            outlineStyle: "solid",
            outlineColor: "#dde2e8",
            outlineWidth: 1,
            outlineOffset: -0.5,
          }}
        />
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 15,
            flexShrink: 0,
          }}
        >
          <div
            style={{
              position: "relative",
              width: 30,
              flexShrink: 0,
              height: 30,
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 0,
                width: 30,
                top: 0,
                height: 30,
                borderRadius: "50%",
              }}
              src="/svg_17.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 9,
                width: "max-content",
                top: 3,
                color: "#ffffff",
                fontSize: 18,
                fontWeight: 500,
              }}
            >
              3
            </p>
          </div>
          <p
            style={{
              width: "max-content",
              flexShrink: 0,
              color: "#c6c2c2",
              fontSize: 22.780000686645508,
              fontWeight: 700,
            }}
          >
            Confirmation
          </p>
        </div>
      </div>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 100,
          position: "absolute",
          left: "50%",
          top: "50%",
          transform: "translateX(-472px) translateY(-489px)",
        }}
      >
        <div
          style={{
            display: "flex",
            gap: 5,
            flexShrink: 0,
          }}
        >
          <p
            style={{
              width: "max-content",
              flexShrink: 0,
              color: "#727272",
              fontSize: 25.6299991607666,
              fontWeight: 700,
            }}
          >
            Users /
          </p>
          <p
            style={{
              width: "max-content",
              flexShrink: 0,
              color: "#1ba9a0",
              fontSize: 25.6299991607666,
              fontWeight: 700,
            }}
          >
            Add User
          </p>
        </div>
        <div
          style={{
            position: "relative",
            width: 330,
            flexShrink: 0,
            height: 46,
            backgroundColor: "#ffffff",
            zIndex: 0,
            outlineStyle: "solid",
            outlineColor: "#dde2e8",
            outlineWidth: 1,
            outlineOffset: -1,
            borderRadius: 30,
            overflow: "hidden",
          }}
        >
          <p
            style={{
              position: "absolute",
              left: 15,
              width: "max-content",
              top: "50%",
              color: "#727272",
              zIndex: -1,
              fontSize: 14.220000267028809,
              fontWeight: 400,
              transform: "translateY(-10px)",
            }}
          >
            Search anything here...
          </p>
          <img
            style={{
              position: "absolute",
              right: 15,
              width: 18,
              top: "50%",
              height: 18,
              zIndex: -1,
              overflow: "hidden",
              transform: "translateY(-9px)",
            }}
            src="/svg_18.svg"
            alt=""
          />
        </div>
      </div>
      <div
        style={{
          position: "absolute",
          left: 0,
          width: 218,
          top: 0,
          height: 1024,
          backgroundColor: "#ffffff",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            gap: -7.672839164733887,
            position: "absolute",
            left: 87.99996185302734,
            top: 50,
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: -11.271140098571777,
              height: 25.76260757446289,
              flexShrink: 0,
            }}
          >
            <div
              style={{
                position: "relative",
                width: 19.32195472717285,
                flexShrink: 0,
                height: 19.32195472717285,
                overflow: "hidden",
                transform: "rotate(-35deg)",
              }}
            >
              <img
                style={{
                  position: "absolute",
                }}
                src="/svg_19.svg"
                alt=""
              />
            </div>
            <div
              style={{
                position: "relative",
                width: 19.32195472717285,
                flexShrink: 0,
                height: 19.32195472717285,
                overflow: "hidden",
                transform: "rotate(35deg)",
              }}
            >
              <img
                style={{
                  position: "absolute",
                }}
                src="/svg_20.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: -11.271140098571777,
              flexShrink: 0,
            }}
          >
            <div
              style={{
                position: "relative",
                width: 19.32195472717285,
                flexShrink: 0,
                height: 19.32195472717285,
                overflow: "hidden",
                transform: "rotate(-35deg)",
              }}
            >
              <img
                style={{
                  position: "absolute",
                }}
                src="/svg_21.svg"
                alt=""
              />
            </div>
            <div
              style={{
                position: "relative",
                width: 19.32195472717285,
                flexShrink: 0,
                height: 19.32195472717285,
                overflow: "hidden",
                transform: "rotate(35deg)",
              }}
            >
              <img
                style={{
                  position: "absolute",
                }}
                src="/svg_22.svg"
                alt=""
              />
            </div>
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 20,
            width: 178,
            top: 824,
            height: 40,
            backgroundColor: "#fbf9f7",
            borderRadius: 8,
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 5,
              width: 82,
              top: 5,
              height: 30,
              backgroundColor: "#ffffff",
              borderRadius: 4,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 11,
                top: 6,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 18,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_23.svg"
                alt=""
              />
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#1ba9a0",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Light
              </p>
            </div>
          </div>
          <div
            style={{
              position: "absolute",
              left: 91,
              width: 82,
              top: 5,
              height: 30,
              borderRadius: 4,
              overflow: "hidden",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: 10,
                position: "absolute",
                left: 12,
                top: 6,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 16,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_24.svg"
                alt=""
              />
              <p
                style={{
                  width: "max-content",
                  flexShrink: 0,
                  color: "#727272",
                  fontSize: 14.220000267028809,
                  fontWeight: 400,
                }}
              >
                Dark
              </p>
            </div>
          </div>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 8,
            position: "absolute",
            left: 20,
            top: 125,
          }}
        >
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_25.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Home
            </p>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_26.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Analytics
            </p>
          </div>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 8,
            position: "absolute",
            left: 20,
            top: 380,
          }}
        >
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_27.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              User Profile
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_28.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_29.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Account
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_30.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_31.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              E-commerce
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_32.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_33.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Projects
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_34.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_35.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Authentication
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_36.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_37.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Kanban
            </p>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_38.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Calendar
            </p>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_39.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Invoice{" "}
            </p>
          </div>
          <div
            style={{
              position: "relative",
              height: 40,
              flexShrink: 0,
              width: 178,
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 14,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_40.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#727272",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Messages
            </p>
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 20,
            width: 178,
            top: 221,
            height: 151,
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              width: 178,
              top: 0,
              height: 40,
              backgroundColor: "#1ba9a0",
              borderRadius: 8,
              overflow: "hidden",
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 15,
                width: 16,
                top: 13,
                height: 14,
                overflow: "hidden",
              }}
              src="/svg_41.svg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 39,
                width: "max-content",
                top: 12,
                color: "#ffffff",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Users
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "flex-end",
                gap: 8,
                position: "absolute",
                right: 15,
                top: 12,
              }}
            >
              <img
                style={{
                  position: "relative",
                  width: 15.75,
                  flexShrink: 0,
                  height: 18,
                  overflow: "hidden",
                }}
                src="/svg_42.svg"
                alt=""
              />
            </div>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 1,
              position: "absolute",
              left: 25,
              top: 48,
            }}
          >
            <img
              style={{
                width: 0,
                flexShrink: 0,
                height: 90.5,
              }}
              src="/svg_43.svg"
              alt=""
            />
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: 8,
                flexShrink: 0,
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  paddingLeft: 16,
                  paddingRight: 16,
                  paddingTop: 5,
                  paddingBottom: 5,
                  flexShrink: 0,
                }}
              >
                <p
                  style={{
                    width: "max-content",
                    flexShrink: 0,
                    color: "#727272",
                    fontSize: 14.220000267028809,
                    fontWeight: 400,
                  }}
                >
                  Overview
                </p>
              </div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  paddingLeft: 16,
                  paddingRight: 16,
                  paddingTop: 5,
                  paddingBottom: 5,
                  flexShrink: 0,
                }}
              >
                <p
                  style={{
                    width: "max-content",
                    flexShrink: 0,
                    color: "#727272",
                    fontSize: 14.220000267028809,
                    fontWeight: 400,
                  }}
                >
                  Leaderboard
                </p>
              </div>
              <div
                style={{
                  display: "flex",
                  justifyContent: "center",
                  alignItems: "center",
                  gap: 10,
                  paddingLeft: 16,
                  paddingRight: 16,
                  paddingTop: 5,
                  paddingBottom: 5,
                  flexShrink: 0,
                }}
              >
                <p
                  style={{
                    width: "max-content",
                    flexShrink: 0,
                    color: "#1ba9a0",
                    fontSize: 14.220000267028809,
                    fontWeight: 400,
                  }}
                >
                  Add user
                </p>
              </div>
            </div>
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 28,
            width: 162,
            bottom: 30,
            height: 47,
            backgroundColor: "#1ba9a0",
            borderRadius: 6,
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 9,
              width: 91,
              top: 7,
              height: 33,
            }}
          >
            <img
              style={{
                position: "absolute",
                left: 0,
                width: 32,
                top: 0,
                height: 32,
                borderRadius: 30,
                overflow: "hidden",
              }}
              src="/img_44.jpg"
              alt=""
            />
            <p
              style={{
                position: "absolute",
                left: 38.6279296875,
                width: "max-content",
                top: 7.28125,
                color: "#ffffff",
                fontSize: 14.220000267028809,
                fontWeight: 400,
              }}
            >
              Sulzine
            </p>
          </div>
          <img
            style={{
              position: "absolute",
              left: 133,
              width: 14,
              top: 16,
              height: 16,
              overflow: "hidden",
            }}
            src="/svg_45.svg"
            alt=""
          />
        </div>
      </div>
    </div>
  );
}
