/**
 * File generated by Figma Launchpad plugin
 * https://www.figma.com/community/plugin/1198744392213971918
 */
import React, { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";

import App from "./App.js";

const root = createRoot(document.getElementById("root"));
root.render(
  <StrictMode>
    <App />
  </StrictMode>
);
